apiVersion: v1
kind: Service
metadata: 
  name: result
  labels: 
    app: result
spec: 
  type: NodePort
  ports: 
    - name: "result-service"
      targetPort: 80
      port: 8081
      nodePort: 31001
  selector:
    app: result
