apiVersion: v1
kind: Service
metadata: 
  name: vote
  labels: 
    app: vote
spec: 
  type: NodePort
  ports: 
    - name: "voting-service"
      targetPort: 80
      port: 8080
  selector:
    app: vote
