pipeline {
    agent any
    stages {
        stage("Clean Up"){
            steps{
                deleteDir()
            }
        }
        stage("Clone Repo"){
            steps{
                sh " git clone https://github.com/HemanthIlluri/Devops.git"
            }
        }
        stage("Build"){
            steps{
                dir("Devops"){
                    sh"mvn clean install"	        
		}
            }
        }
        stage("Test"){
            steps{
                dir("Devops"){
                    sh"test"  
                }
            }
        }
    }
}
